<div class="col-6_sm-12 storycard--background" style="background: rgba(0,0,0,1) url(/view/image/fieldnotes/test-selling-online_file_3.jpg) no-repeat center; background-size: auto;border-radius: 6px;">
<div style="padding: 5px;padding-left: 2rem;/* display: flex; */background-color: rgba(0, 0, 0, 0.5);padding-top: 1rem;"><p style="font-size: .7rem;">FILMSTRIP</p><h4 style="color: #FFFFFF;">Wonders of Lake Tahoe</h4><p style="font-size: .7rem;">By James McCarthy — August 05, 2020</p></div>
<div class="content--preview" style="display: flex;">                        
<div style="flex: 1;margin-right: 1rem;"><img style="height: 120px;" src="/view/image/fieldnotes/test-selling-online_file_2.jpg"></div><div style="flex: 1;margin-right: 1rem;"><img style="height: 120px;" src="/view/image/fieldnotes/test-selling-online_file_3.jpg"></div><div style="flex: 1;"><img style="height: 120px;" src="/view/image/fieldnotes/test-selling-online_file_2.jpg"></div><div style="flex:1;font-size: 4rem;padding-top: 2rem;text-align: center;padding-left: 2rem;em;"><i class="fas fa-angle-right" aria-hidden="true"></i></div></div>
</div>

/* Expanded */
<div class="col-6_sm-12 storycard--background" style="/*background: rgba(0,0,0,1) url(/view/image/fieldnotes/test-selling-online_file_3.jpg) no-repeat center;*/ background-size: auto; background-color: #000;">
<div style="padding: 5px;padding-left: 2rem; background-color: rgba(0, 0, 0, 0.5);padding-top: 1rem;"><p style="font-size: .7rem;">FILMSTRIP</p><h4 style="color: #FFFFFF;">Wonders of Lake Tahoe</h4><p style="font-size: .7rem;">By James McCarthy — August 05, 2020</p></div>
<div class="content--preview" style="display: flex;">                        
<div style="flex: 1;margin-right: 1rem;"><img style="height: 120px;" src="/view/image/fieldnotes/test-selling-online_file_2.jpg"></div><div style="flex: 1;margin-right: 1rem;"><img style="height: 120px;border-bottom: 4px solid rgba(255,255,255,.5);padding-bottom: 10px;" src="/view/image/fieldnotes/test-selling-online_file_3.jpg"></div><div style="flex: 1;margin-right: 1rem;"><img style="height: 120px;" src="/view/image/fieldnotes/test-selling-online_file_2.jpg"></div><div style="flex: 1;"><img style="height: 120px;" src="/view/image/fieldnotes/test-selling-online_file_2.jpg"></div><!-- <div style="flex:1;font-size: 4rem;padding-top: 2rem;text-align: center;padding-left: 2rem;em;"><i class="fas fa-angle-right" aria-hidden="true"></i></div>--></div>
<div style="background-color: #000; min-height:300px;position: relative;"><img style="width: 100%;" src="/view/image/fieldnotes/test-selling-online_file_3.jpg"><p style="background-color: rgba(255,255,255,.5); text-align: right;padding: 1rem;position: absolute;top: 0;right: 0;color: #000;"><i class="fas fa-times-circle" aria-hidden="true"></i></p></div><div style="background-color: #000;"><p style="padding: 1rem;">Donec sed odio dui. Cras mattis consectetur purus sit amet fermentum. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec sed odio dui. Cras mattis consectetur purus sit amet fermentum. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec sed odio dui. Cras mattis consectetur purus sit amet fermentum. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p></div>
</div>